### ISSUE TITLE
Which framework is suitable to Frontend?

### ISSUE THREAD

**Issue by jaewan7599** [skkuse02/2019fall_41class_team4#1]
I think this is dependent on Frontend Developmer, 주혜원, and developing language that she want to use. Let's discuss about it.

**Comment by jaewan7599** [comment]
We have to make sure about frontend framework, because it affects to our system architecture.

**Comment by hyednjs** [comment]
We can use React as javascript framework.

**Comment by jaewan7599** [comment]
Can it handle DB connection?
