### ISSUE TITLE
generate design specification documentation of PICKET

### ISSUE THREAD

**Issue by kwk2696** [skkuse02/2019fall_41class_team4#3]
1. analysis general structures of PICEKT
2. generate design specification document 
due date: 2019.11.10

**Comment by hyednjs** [comment]
Role
1.	Preface _ Kim
2.	Introduction _ Kim
3.	System Architecture _ overall _ moon
4.	System Architecture _ front _ Ju
5.	System Architecture _ back _ sung
6.	Protocol Design _ sung
7.	Database Design _ moon
8.	Testing Plan _ Ju
9.	Development Plan _ Kim
10.	 Index _ Kim
