### ISSUE TITLE
About System Architecture

### ISSUE THREAD

**Issue by jaewan7599** [skkuse02/2019fall_41class_team4#5]
I think we have pre-written system architecture that exists in our proposal. Let's discuss about which one should be changed, and which one can be reused.

**Comment by jaewan7599** [comment]
I write overall architecture for our system. I can't upload picture in here, so please check your messenger.

**Comment by tjdckdals** [comment]
let's make design specification

**Comment by tjdckdals** [comment]
my part is system architecture backend and protocol
